language: android
sudo: required
env:
  global:
    - ADB_INSTALL_TIMEOUT=8 # 8 minutes (2 minutes by default)

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - build-tools-25.0.1
    - android-25
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-19

before_script:
    - mkdir app/src/main/res/raw
    - mv app/config/survey.properties.template app/src/main/res/raw/survey.properties
    - mv app/gradle.properties.template app/gradle.properties
    - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
    - emulator -avd test -no-audio -no-window &
    - android-wait-for-emulator
    - adb shell settings put global window_animation_scale 0 &
    - adb shell settings put global transition_animation_scale 0 &
    - adb shell settings put global animator_duration_scale 0 &
    - adb shell input keyevent 82 &

script:
  - ./gradlew check -PdisablePreDex --continue --stacktrace -Pcom.android.build.threadPoolSize=1 -Dorg.gradle.parallel=false -Dorg.gradle.jvmargs="-Xms1024m -Xmx1024m" -Dorg.gradle.daemon=false
  - ./gradlew testFlowDebug -PdisablePreDex --continue --stacktrace -Pcom.android.build.threadPoolSize=1 -Dorg.gradle.parallel=false -Dorg.gradle.jvmargs="-Xms1024m -Xmx1024m" -Dorg.gradle.daemon=false
  
after_failure:
  - sudo apt-get install pandoc -y
  - pandoc app/build/reports/tests/flowDebug/index.html -t plain | sed -n '/^Failed tests/,/default-package/p'
  
after_success:
  - ./gradlew createFlowDebugCoverageReport -PdisablePreDex --continue --stacktrace -Pcom.android.build.threadPoolSize=1 -Dorg.gradle.parallel=false -Dorg.gradle.jvmargs="-Xms1024m -Xmx1024m" -Dorg.gradle.daemon=false
  - bash <(curl -s https://codecov.io/bash)

